return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      ["javascript"] = { "prettierd", "prettier" },
      ["javascriptreact"] = { "prettierd", "prettier" },
      ["typescript"] = { "prettierd", "prettier" },
      ["typescriptreact"] = { "prettierd", "prettier" },
      ["vue"] = { "prettierd", "prettier" },
      ["css"] = { "prettierd", "prettier" },
      ["scss"] = { "prettierd", "prettier" },
      ["less"] = { "prettier" },
      ["html"] = { "prettierd", "prettier" },
      ["json"] = { "prettierd", "prettier" },
      ["jsonc"] = { "prettier" },
      ["yaml"] = { "prettier" },
      ["markdown"] = { "prettier" },
      ["markdown.mdx"] = { "prettier" },
      ["graphql"] = { "prettier" },
      ["handlebars"] = { "prettier" },
      ["htmldjango"] = { "prettier" },
      ["astro"] = { "prettier" },
      ["rust"] = { "rustfmt" },
      ["svg"] = { "prettier" },
    },
  },
}
