return {}
-- return {
--   import = "lazyvim.plugins.extras.lsp.none-ls",
--   opts = function(_, opts)
--     local nls = require("null-ls")
--     opts.root_dir = opts.root_dir
--       or require("null-ls.utils").root_pattern(".null-ls-root", ".neoconf.json", "Makefile", ".git")
--     opts.sources = vim.list_extend(opts.sources or {}, {
--       nls.builtins.formatting.fish_indent,
--       nls.builtins.diagnostics.fish,
--       nls.builtins.formatting.stylua,
--       nls.builtins.formatting.shfmt,
--       nls.builtins.formatting.stylua,
--       nls.builtins.diagnostics.eslint,
--       -- nls.builtins.completion.spell,
--       -- nls.builtins.formatting.prettier.with({
--       --   extra_filetypes = { "htmldjango" },
--       -- }),
--       nls.builtins.formatting.prettierd,
--       nls.builtins.formatting.rustfmt,
--       nls.builtins.formatting.pg_format,
--       -- nls.builtins.diagnostics.curlylint,
--       nls.builtins.formatting.djhtml.with({
--         extra_args = { "--tabwidth", 2 },
--       }),
--       nls.builtins.diagnostics.djlint,
--     })
--   end,
-- }
